### PR TITLE
adding unit and name attributes to layers

### PR DESCRIPTION
**Pull request by prayner**
addresses #16

-------

## Checklist

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)
 

## Notes

### CODE REVIEW

**Review by lewisjared — COMMENTED** [review]
I think we need to add the required attributes to the total as well as the layers in the `sum_layers` function.

We should also add a test to the `test_om_prior.py` which verifies that the units are in the output. This helps to ensure that they don't get lost if we do further changes. This one is a bit annoying because it requires running the whole workflow to test this so it can be a bit slow.

A simple test like this could be sufficient for now:

```
def test_required_attributes(output_domain_xr):
    assert output_domain_xr.variables["OCH4_TOTAL"].attrs == {
        "units": "kg/m^2/s",
        "long_name": "OCH4_TOTAL",
    }
    assert output_domain_xr.variables["OCH4_WETLANDS"].attrs == {
        "units": "kg/m^2/s",
        "long_name": "OCH4_WETLANDS",
    }
```

This currently fails until the fix to the total has been implemented.

We should have a session on how to run [pytest](https://docs.pytest.org/en/8.2.x/) and the test suite.

**Comment by prayner** [comment]
added the attributes, I'll leave the test to someone who understands pytest

**Comment by lewisjared** [comment]
@prayner Are you able to see any line-specific comments or are they not available in emacs?

**Comment by prayner** [comment]
Don't think I can see them in emacs ... let's see if the gh cli
reveals them

**Comment by prayner** [comment]
I'm not seeing in-line comments, are there some here?

**Review by lewisjared — APPROVED** [review]
Ok good to know.

For constants, "SCREAMING_SNAKE_CASE" is the preference. If we don't change this as part of this PR it will likely later be cleaned up.

I had another comment to use `setncatts` to set all the values at the same time instead of looping.

I'll fix them up with the tests

**Comment by lewisjared** [comment]
@prayner Can I add the tests to this branch? If so please assign this PR to me

**Pull request merged**
