### PR TITLE
Fixups to location-fix

### PR DESCRIPTION
**Pull request by lewisjared**
## Description

Some tweaks to #42. Mostly from running `make ruff-fixes`, but other notable changes include:
* moving `remap_raster` into `raster.py`
* Refactoring the reprojection test into a format expected by pytest

## Checklist

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)

### CODE REVIEW

**Comment by lewisjared** [comment]
@prayner Take a look at this commit showing how test code can be refactored into something that pytest can use. https://github.com/openmethane/openmethane-prior/commit/f77e2d475022e550e35b5ab17c489d02eb2197fc

Namely:
* Move code into a function that starts with `test_`
* Use [pytest fixtures](https://docs.pytest.org/en/6.2.x/fixture.html) for common functionality (e.g. configuration). See `conftest.py` for some project-specific fixtures

**Comment by lewisjared** [comment]
@prayner There is a ~30% difference in electricity emissions compared to the total. Is that expected?

**Comment by prayner** [comment]
It's 30% of 0.01 when our fossil target is about 1 so I don't *think*
it's a problem to worry about. That said I'll try to work out what's
being masked. I suspect one gas-fired plant in South Australia which
CMAQ is probably dropping in the ocean. I'll check but if that's the
problem will turn off land masking for that sector.
-- 
Peter Rayner (he/him), Honorary Professorial Fellow, University of Melbourne
mobile +61 402 752 379
zoom id 4431343191, join at  <https://unimelb.zoom.us/j/4431343191?pwd=a1E5Z3JEOTRVQUJsaVdRbVUvR1QyZz09>
mail-to: ***@***.***
google scholar: <https://scholar.google.com.au/citations?user=H3up71wAAAAJ&hl=en>
I acknowledge the Traditional Custodians of the land on which I work, the Wurundjeri people of the Kulin nation, and pay my respect to their Elders, past and present
I am sending this email when convenient for me, please only respond when convenient for you

**Comment by lewisjared** [comment]
I'll merge for now and then we can always resolve later

**Pull request merged**
