### PR TITLE
Update license headers

### PR DESCRIPTION
**Pull request by lewisjared**
## Description

Uses a template file for adding the license headers to all source files. The long lines were causing havoc with ruff.

The Apache2 template from [licenseheaders](https://github.com/johann-petrak/licenseheaders/blob/master/templates/apache-2.tmpl) was used.

The license header can be updated/added to all all files using `make update-licenseheaders`

## Checklist

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)

### CODE REVIEW

**Comment by lewisjared** [comment]
Fixed the merge conflict so this is ready for review

**Comment by lewisjared** [comment]
@prayner Can I have a review please

**Comment by lewisjared** [comment]
@prayner ping. No code changes here just the header comment

**Comment by aethr** [comment]
@lewisjared from a quick review of the license headers being updated, it looks like this changes the copyright year from 2023 to 2024. Ideally the year shouldn't change, so the copyright is "active" from when the file was created.

**Pull request merged**
